# Specifica che stiamo usando il database H2 in memoria
# spring.datasource.url=jdbc:h2:mem:hackhubdb
spring.datasource.url=jdbc:h2:file:./data/hackhubdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dice a Spring (tramite Hibernate) di creare/aggiornare automaticamente le tabelle in base al codice Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Abilita una comoda interfaccia web per vedere il database dal browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Imposta il path base per la documentazione
springdoc.api-docs.path=/api-docs
# Mostra Swagger UI (l'interfaccia grafica)
springdoc.swagger-ui.path=/swagger-ui.html